apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-trishul
resources:
  - namespace.yaml
  - config.yaml
  - rbac.yaml
  - edge.yaml
  - workloads.yaml
  - policies.yaml
  - availability.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: ai-trishul
    includeSelectors: true
