# Generated by Django 6.0.7 on 2026-08-06 11:33

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_job_application"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionThresholdProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=120)),
                ("profile_version", models.CharField(default="1.0.0", max_length=40)),
                (
                    "block_at_risk",
                    models.DecimalField(decimal_places=2, default=70, max_digits=5),
                ),
                (
                    "manual_review_at_risk",
                    models.DecimalField(decimal_places=2, default=50, max_digits=5),
                ),
                (
                    "actions_at_risk",
                    models.DecimalField(decimal_places=2, default=25, max_digits=5),
                ),
                ("block_critical_on_production", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "da_threshold_profile",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="DeploymentTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=120)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("aws", "Amazon Web Services"),
                            ("azure", "Microsoft Azure"),
                            ("gcp", "Google Cloud"),
                            ("kubernetes", "Kubernetes"),
                            ("vmware", "VMware"),
                            ("on_prem", "On-premises"),
                            ("generic", "Provider-neutral"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("account", "Cloud account"),
                            ("subscription", "Subscription"),
                            ("project", "Project"),
                            ("cluster", "Cluster"),
                            ("server", "Server"),
                            ("server_group", "Server group"),
                            ("application_stack", "Application stack"),
                            ("iac_deployment", "IaC deployment"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("development", "Development"),
                            ("test", "Test"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                        ],
                        max_length=20,
                    ),
                ),
                ("external_id", models.CharField(max_length=400)),
                ("region", models.CharField(blank=True, max_length=80)),
                (
                    "criticality",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "data_sensitivity",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("internet_exposed", models.BooleanField(default=False)),
                ("owner_reference", models.CharField(blank=True, max_length=200)),
                ("labels", models.JSONField(blank=True, default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("decommissioning", "Decommissioning"),
                            ("decommissioned", "Decommissioned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("baseline_snapshot_id", models.UUIDField(blank=True, null=True)),
                ("last_observed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployment_targets",
                        to="core.application",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "da_deployment_target",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="DeploymentSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("terraform_plan", "Terraform plan JSON"),
                            ("kubernetes_manifest", "Kubernetes manifest YAML"),
                            ("compose_file", "Docker Compose YAML"),
                            ("server_inventory", "Normalized server inventory JSON"),
                            ("cloud_inventory", "Provider inventory collection"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source_reference", models.CharField(blank=True, max_length=400)),
                ("source_revision", models.CharField(blank=True, max_length=120)),
                ("artifact_object_key", models.CharField(max_length=600)),
                ("artifact_sha256", models.CharField(max_length=64)),
                ("artifact_size", models.PositiveBigIntegerField()),
                (
                    "media_type",
                    models.CharField(
                        default="application/octet-stream", max_length=120
                    ),
                ),
                (
                    "schema_version",
                    models.CharField(default="trishul-snapshot/1.0", max_length=60),
                ),
                ("normalized_object_key", models.CharField(blank=True, max_length=600)),
                ("normalized_sha256", models.CharField(blank=True, max_length=64)),
                ("resource_count", models.PositiveIntegerField(default=0)),
                (
                    "collected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "collected_by_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("service_account", "Service account"),
                            ("connector", "Connector"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("collected_by_id", models.CharField(blank=True, max_length=200)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "ingestion_state",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("validating", "Validating"),
                            ("ready", "Ready"),
                            ("rejected", "Rejected"),
                        ],
                        default="uploading",
                        max_length=20,
                    ),
                ),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="deployment_assurance.deploymentsnapshot",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="deployment_assurance.deploymenttarget",
                    ),
                ),
            ],
            options={
                "db_table": "da_deployment_snapshot",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EvaluationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("pull_request", "Pull request"),
                            ("pre_deploy", "Pre-deployment"),
                            ("post_deploy", "Post-deployment"),
                            ("scheduled", "Scheduled"),
                            ("drift", "Drift check"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("normalizing", "Normalizing"),
                            ("evaluating", "Evaluating"),
                            ("deciding", "Deciding"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(blank=True, max_length=200)),
                ("correlation_id", models.UUIDField(default=uuid.uuid4)),
                (
                    "requested_by_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("service_account", "Service account"),
                            ("connector", "Connector"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("requested_by_id", models.CharField(blank=True, max_length=200)),
                ("input_hash", models.CharField(blank=True, max_length=64)),
                ("policy_hash", models.CharField(blank=True, max_length=64)),
                ("engine_versions", models.JSONField(blank=True, default=dict)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("result_manifest_key", models.CharField(blank=True, max_length=600)),
                ("result_manifest_hash", models.CharField(blank=True, max_length=64)),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("summary", models.JSONField(blank=True, default=dict)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluations",
                        to="deployment_assurance.deploymentsnapshot",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluations",
                        to="deployment_assurance.deploymenttarget",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "da_evaluation_run",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="DriftEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("introduced_fingerprints", models.JSONField(default=list)),
                ("resolved_fingerprints", models.JSONField(default=list)),
                (
                    "risk_delta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("remediating", "Remediating"),
                            ("resolved", "Resolved"),
                            ("accepted", "Accepted"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("resolution", models.TextField(blank=True, max_length=4000)),
                (
                    "baseline_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baseline_drift_events",
                        to="deployment_assurance.deploymentsnapshot",
                    ),
                ),
                (
                    "observed_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observed_drift_events",
                        to="deployment_assurance.deploymentsnapshot",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drift_events",
                        to="deployment_assurance.deploymenttarget",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "evaluation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drift_events",
                        to="deployment_assurance.evaluationrun",
                    ),
                ),
            ],
            options={
                "db_table": "da_drift_event",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="DeploymentDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("approved_with_actions", "Approved with actions"),
                            ("manual_review", "Manual review"),
                            ("blocked", "Blocked"),
                            ("error", "Evaluation error"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "compliance_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "risk_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("reason_codes", models.JSONField(default=list)),
                ("counts", models.JSONField(default=dict)),
                ("decision_hash", models.CharField(max_length=64)),
                (
                    "finalized_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supersedes",
                        to="deployment_assurance.deploymentdecision",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "threshold_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="deployment_assurance.decisionthresholdprofile",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="deployment_assurance.deploymenttarget",
                    ),
                ),
                (
                    "evaluation_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decision",
                        to="deployment_assurance.evaluationrun",
                    ),
                ),
            ],
            options={
                "db_table": "da_deployment_decision",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("source_artifact", "Source artifact"),
                            ("normalized_snapshot", "Normalized snapshot"),
                            ("result_manifest", "Result manifest"),
                            ("decision_envelope", "Decision envelope"),
                        ],
                        max_length=30,
                    ),
                ),
                ("object_key", models.CharField(max_length=600)),
                (
                    "media_type",
                    models.CharField(default="application/json", max_length=120),
                ),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("envelope", models.JSONField(default=dict)),
                (
                    "classification",
                    models.CharField(default="confidential", max_length=40),
                ),
                (
                    "retention_class",
                    models.CharField(
                        default="deployment-evidence-default", max_length=60
                    ),
                ),
                ("legal_hold", models.BooleanField(default=False)),
                (
                    "evaluation_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="deployment_assurance.evaluationrun",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="deployment_assurance.deploymentsnapshot",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="deployment_assurance.deploymenttarget",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "da_evidence_artifact",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PolicyPack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("key", models.CharField(max_length=80)),
                ("pack_version", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, max_length=4000)),
                ("content_hash", models.CharField(max_length=64)),
                ("signing_identity", models.CharField(blank=True, max_length=200)),
                ("engine_version", models.CharField(max_length=40)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "da_policy_pack",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="evaluationrun",
            name="policy_pack",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="deployment_assurance.policypack",
            ),
        ),
        migrations.CreateModel(
            name="PolicyProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=120)),
                ("excluded_rule_keys", models.JSONField(blank=True, default=list)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "policy_pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profiles",
                        to="deployment_assurance.policypack",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "threshold_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="deployment_assurance.decisionthresholdprofile",
                    ),
                ),
            ],
            options={
                "db_table": "da_policy_profile",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="evaluationrun",
            name="policy_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="deployment_assurance.policyprofile",
            ),
        ),
        migrations.AddField(
            model_name="deploymenttarget",
            name="policy_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="deployment_assurance.policyprofile",
            ),
        ),
        migrations.CreateModel(
            name="PolicyRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("stable_key", models.CharField(max_length=40)),
                ("rule_version", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=4000)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("network", "Network"),
                            ("identity", "Identity"),
                            ("encryption", "Encryption"),
                            ("logging", "Logging"),
                            ("backup", "Backup"),
                            ("vulnerability", "Vulnerability"),
                            ("configuration", "Configuration"),
                            ("supply_chain", "Supply chain"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("entrypoint", models.CharField(max_length=200)),
                ("resource_types", models.JSONField(default=list)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("remediation_guidance", models.TextField(max_length=4000)),
                (
                    "automation_class",
                    models.CharField(
                        choices=[
                            ("guidance", "Guidance only"),
                            ("patch", "Patch generation"),
                            ("approval_required", "Approval-required execution"),
                            ("autonomous_safe", "Autonomous safe"),
                        ],
                        default="guidance",
                        max_length=30,
                    ),
                ),
                ("blocking", models.BooleanField(default=False)),
                ("content_hash", models.CharField(max_length=64)),
                ("active", models.BooleanField(default=True)),
                (
                    "policy_pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rules",
                        to="deployment_assurance.policypack",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
            ],
            options={
                "db_table": "da_policy_rule",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ExceptionWaiver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("rule_version", models.CharField(max_length=40)),
                ("resource_fingerprint", models.CharField(max_length=64)),
                ("reason", models.TextField(max_length=4000)),
                ("compensating_controls", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True, max_length=4000)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployment_waiver_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployment_waiver_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waivers",
                        to="deployment_assurance.deploymenttarget",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "policy_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waivers",
                        to="deployment_assurance.policyrule",
                    ),
                ),
            ],
            options={
                "db_table": "da_exception_waiver",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ControlResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("resource_type", models.CharField(max_length=80)),
                ("resource_id", models.CharField(max_length=400)),
                ("resource_path", models.CharField(blank=True, max_length=600)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("fail", "Fail"),
                            ("warning", "Warning"),
                            ("not_applicable", "Not applicable"),
                            ("not_evaluated", "Not evaluated"),
                            ("error", "Error"),
                            ("manual_review", "Manual review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason_code", models.CharField(max_length=80)),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(
                        default=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("rationale", models.TextField(max_length=4000)),
                ("expected", models.JSONField(blank=True, default=dict)),
                ("observed", models.JSONField(blank=True, default=dict)),
                ("fingerprint", models.CharField(max_length=64)),
                ("blocking", models.BooleanField(default=False)),
                (
                    "residual_risk",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployment_results",
                        to="core.risk",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "evaluation_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="deployment_assurance.evaluationrun",
                    ),
                ),
                (
                    "waived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="deployment_assurance.exceptionwaiver",
                    ),
                ),
                (
                    "policy_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="deployment_assurance.policyrule",
                    ),
                ),
            ],
            options={
                "db_table": "da_control_result",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ControlMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("framework", models.CharField(max_length=80)),
                ("framework_version", models.CharField(max_length=40)),
                ("control_id", models.CharField(max_length=80)),
                ("note", models.CharField(blank=True, max_length=400)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "policy_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mappings",
                        to="deployment_assurance.policyrule",
                    ),
                ),
            ],
            options={
                "db_table": "da_control_mapping",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="decisionthresholdprofile",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name", "profile_version"),
                name="da_threshold_profile_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="deploymentsnapshot",
            index=models.Index(
                fields=["tenant", "target", "-created_at"],
                name="da_snapshot_target_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="driftevent",
            index=models.Index(
                fields=["tenant", "target", "status"], name="da_drift_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deploymentdecision",
            index=models.Index(
                fields=["tenant", "target", "-created_at"],
                name="da_decision_target_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceartifact",
            constraint=models.UniqueConstraint(
                fields=("tenant", "object_key"), name="da_evidence_object_key_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="policypack",
            constraint=models.UniqueConstraint(
                fields=("tenant", "key", "pack_version"), name="da_policy_pack_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyprofile",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="da_policy_profile_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="evaluationrun",
            index=models.Index(
                fields=["tenant", "target", "-created_at"],
                name="da_evaluation_target_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__gt", "")),
                fields=("tenant", "idempotency_key"),
                name="da_evaluation_idempotency_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="deploymenttarget",
            constraint=models.UniqueConstraint(
                fields=("tenant", "provider", "external_id"),
                name="da_target_external_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="deploymenttarget",
            constraint=models.UniqueConstraint(
                fields=("tenant", "application", "slug"), name="da_target_slug_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyrule",
            constraint=models.UniqueConstraint(
                fields=("tenant", "policy_pack", "stable_key"),
                name="da_policy_rule_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="exceptionwaiver",
            index=models.Index(
                fields=["tenant", "target", "status"], name="da_waiver_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="controlresult",
            index=models.Index(
                fields=["tenant", "evaluation_run", "outcome"],
                name="da_result_outcome_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="controlresult",
            constraint=models.UniqueConstraint(
                fields=("tenant", "evaluation_run", "fingerprint"),
                name="da_control_result_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="controlmapping",
            constraint=models.UniqueConstraint(
                fields=(
                    "tenant",
                    "policy_rule",
                    "framework",
                    "framework_version",
                    "control_id",
                ),
                name="da_control_mapping_uniq",
            ),
        ),
    ]
