# Generated by Django 6.0.7 on 2026-08-06 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_saas_ucf_foundation"),
        ("deployment_assurance", "0002_tenant_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlresult",
            name="gap",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deployment_results",
                to="core.compliancegap",
            ),
        ),
        migrations.AddField(
            model_name="policyrule",
            name="unified_control",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deployment_rules",
                to="core.unifiedcontrolobjective",
            ),
        ),
    ]
