apiVersion: v1
kind: Secret
metadata:
  name: trishul-runtime-secrets
  namespace: ai-trishul
type: Opaque
stringData:
  db_app_password: REPLACE
  redis_password: REPLACE
  s3_access_key: REPLACE
  s3_secret_key: REPLACE
  django_secret_key: REPLACE
  internal_ai_token: REPLACE
  metrics_token: REPLACE
---
apiVersion: v1
kind: Secret
metadata:
  name: trishul-ai-credential
  namespace: ai-trishul
type: Opaque
stringData:
  credential: REPLACE

