output "cluster_name" { value = aws_eks_cluster.main.name }
output "evidence_bucket" { value = local.evidence_bucket_id }
output "kms_key_arn" { value = aws_kms_key.data.arn }
output "postgres_endpoint" { value = aws_db_instance.postgres.address }
output "postgres_master_secret_arn" { value = try(aws_db_instance.postgres.master_user_secret[0].secret_arn, null) }
output "redis_endpoint" { value = aws_elasticache_serverless_cache.redis.endpoint[0].address }
output "runtime_secret_arn" { value = local.runtime_secret_arn }
output "waf_acl_arn" { value = aws_wafv2_web_acl.edge.arn }
output "operations_topic_arn" { value = aws_sns_topic.operations.arn }
output "deploy_codebuild_project" { value = aws_codebuild_project.deploy.name }
output "github_deploy_role_arn" { value = aws_iam_role.github_deploy.arn }
output "application_pod_identity_role_arn" { value = aws_iam_role.application.arn }
output "checkpoint_writer_role_arn" { value = local.checkpoint_writer_role_arn }
output "dr_evidence_bucket" { value = try(aws_s3_bucket.evidence_replica[0].id, null) }
output "dr_evidence_kms_key_arn" { value = try(aws_kms_key.dr[0].arn, null) }
output "dr_db_automated_backups_arn" { value = try(aws_db_instance_automated_backups_replication.postgres[0].id, null) }
