apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - checkpoint.yaml
configMapGenerator:
  - name: trishul-config
    behavior: merge
    envs:
      - aws.env
generatorOptions:
  disableNameSuffixHash: true
