# Generated by Django 6.0.7 on 2026-08-06 13:08

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_job_application"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("source_type", models.CharField(max_length=100)),
                ("source_id", models.UUIDField()),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(max_length=8000)),
                ("outcome", models.CharField(max_length=30)),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="AuditorVerdict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("engagement_id", models.UUIDField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("partially_compliant", "Partially compliant"),
                            ("noncompliant", "Non-compliant"),
                            ("not_applicable", "Not applicable"),
                            ("query_raised", "Query raised"),
                        ],
                        max_length=30,
                    ),
                ),
                ("rationale", models.TextField(max_length=8000)),
                ("evidence_result_id", models.UUIDField(blank=True, null=True)),
                (
                    "finalized_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("locked", models.BooleanField(default=True)),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ControlAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("evidence_scope", models.JSONField(blank=True, default=list)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ControlEvidenceLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("source_type", models.CharField(max_length=100)),
                ("source_id", models.UUIDField()),
                ("source_hash", models.CharField(max_length=64)),
                ("verdict", models.CharField(max_length=30)),
                ("confidence", models.PositiveSmallIntegerField(default=5)),
                ("reason", models.TextField(max_length=4000)),
                ("mapping_version", models.CharField(max_length=80)),
                ("system_generated", models.BooleanField(default=False)),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CrossTenantAccessEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("subject_id", models.CharField(max_length=200)),
                ("object_type", models.CharField(max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=200)),
                ("action", models.CharField(max_length=80)),
                (
                    "decision",
                    models.CharField(
                        choices=[("allow", "Allow"), ("deny", "Deny")], max_length=20
                    ),
                ),
                ("reason", models.CharField(max_length=300)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Engagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=200)),
                ("reference", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("revoked", "Revoked"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("framework_scope", models.JSONField(default=list)),
                ("application_scope", models.JSONField(blank=True, default=list)),
                ("control_scope", models.JSONField(blank=True, default=list)),
                ("closed_reason", models.TextField(blank=True, max_length=4000)),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EngagementMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lead", "Lead auditor"),
                            ("auditor", "Auditor"),
                            ("reviewer", "Reviewer / QA"),
                        ],
                        max_length=20,
                    ),
                ),
                ("framework_scope", models.JSONField(blank=True, default=list)),
                ("control_scope", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EngagementScope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("framework", "Framework"),
                            ("application", "Application"),
                            ("control", "Control"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_reference", models.CharField(max_length=200)),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EngagementStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("from_status", models.CharField(blank=True, max_length=20)),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("revoked", "Revoked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, max_length=4000)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("artefact_type", models.CharField(max_length=80)),
                ("required_attributes", models.JSONField(default=list)),
                (
                    "validity_period_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("sampling_rule", models.JSONField(blank=True, default=dict)),
                ("acceptance_criteria", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Framework",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("code", models.SlugField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("issuing_body", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(default="published", max_length=20)),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="FrameworkControlMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "coverage",
                    models.CharField(
                        choices=[
                            ("full", "Full"),
                            ("partial", "Partial"),
                            ("supporting", "Supporting"),
                            ("none", "None"),
                        ],
                        max_length=20,
                    ),
                ),
                ("delta_condition", models.JSONField(blank=True, default=dict)),
                ("rationale", models.TextField(blank=True, max_length=4000)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=3, default=1, max_digits=4),
                ),
                (
                    "mapping_source",
                    models.CharField(
                        choices=[("expert", "Expert"), ("ai", "AI proposed")],
                        default="expert",
                        max_length=20,
                    ),
                ),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="OrganisationControl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "applicability",
                    models.CharField(default="applicable", max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("evidence_submitted", "Evidence submitted"),
                            ("under_review", "Under review"),
                            ("compliant", "Compliant"),
                            ("partially_compliant", "Partially compliant"),
                            ("noncompliant", "Non-compliant"),
                            ("not_applicable", "Not applicable"),
                        ],
                        default="not_started",
                        max_length=30,
                    ),
                ),
                (
                    "implementation_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "maturity_level",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("key", models.SlugField(max_length=80)),
                ("plan_version", models.CharField(default="1.0", max_length=40)),
                ("name", models.CharField(max_length=160)),
                ("entitlements", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("task_type", models.CharField(max_length=60)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(max_length=8000)),
                ("priority", models.CharField(default="medium", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("review", "Review"),
                            ("completed", "Completed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("source_type", models.CharField(blank=True, max_length=100)),
                ("source_id", models.UUIDField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TenantBranding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("logo_object_key", models.CharField(blank=True, max_length=600)),
                ("primary_color", models.CharField(default="#1d4ed8", max_length=7)),
                ("report_name", models.CharField(blank=True, max_length=160)),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TenantEntitlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("code", models.CharField(max_length=80)),
                ("enabled", models.BooleanField(default=True)),
                ("limit", models.PositiveBigIntegerField(blank=True, null=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TenantInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Organization administrator"),
                            ("ciso", "Security leader"),
                            ("architect", "Security architect"),
                            ("appsec", "Application security engineer"),
                            ("assessor", "Security assessor"),
                            ("developer", "Developer"),
                            ("manager", "Engineering manager"),
                            ("auditor", "Auditor"),
                            ("executive", "Executive"),
                            ("platform_admin", "Platform administrator"),
                            ("firm_admin", "Audit firm administrator"),
                            ("audit_manager", "Audit manager"),
                            ("reviewer", "Reviewer / QA"),
                            ("org_admin", "Auditee administrator"),
                            ("compliance_manager", "Compliance manager"),
                            ("control_owner", "Control owner"),
                            ("risk_owner", "Risk owner"),
                            ("vendor_manager", "Vendor manager"),
                        ],
                        max_length=30,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TenantRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "relationship",
                    models.CharField(
                        choices=[("manages", "Manages"), ("client", "Client")],
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(default="active", max_length=20)),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TenantSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("plan_key", models.CharField(max_length=80)),
                ("plan_version", models.CharField(max_length=40)),
                ("entitlement_snapshot", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("grace", "Grace period"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("trial_started_at", models.DateTimeField(blank=True, null=True)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("grace_ends_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="UnifiedControlObjective",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("code", models.CharField(max_length=80)),
                ("objective_version", models.CharField(default="1.0", max_length=40)),
                ("domain", models.CharField(max_length=80)),
                ("objective", models.TextField(max_length=8000)),
                (
                    "control_type",
                    models.CharField(
                        choices=[
                            ("preventive", "Preventive"),
                            ("detective", "Detective"),
                            ("corrective", "Corrective"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("process", "Process"),
                            ("documentation", "Documentation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("metric", models.CharField(max_length=80)),
                ("quantity", models.PositiveBigIntegerField()),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("idempotency_key", models.CharField(blank=True, max_length=200)),
                ("source_type", models.CharField(blank=True, max_length=100)),
                ("source_id", models.UUIDField(blank=True, null=True)),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="compliancegap",
            options={},
        ),
        migrations.AlterModelOptions(
            name="risklink",
            options={},
        ),
        migrations.AddField(
            model_name="compliancegap",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="compliancegap",
            name="source_fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="evidence",
            name="evidence_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="evidence",
            name="status",
            field=models.CharField(default="current", max_length=20),
        ),
        migrations.AddField(
            model_name="evidence",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="superseded_by",
                to="core.evidence",
            ),
        ),
        migrations.AddField(
            model_name="remediation",
            name="gap",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="remediations",
                to="core.compliancegap",
            ),
        ),
        migrations.AddField(
            model_name="remediation",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="auditee_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("firm_managed", "Firm managed"),
                    ("self_service", "Self service"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="isolation_tier",
            field=models.CharField(
                choices=[
                    ("shared", "Shared SaaS"),
                    ("enterprise", "Enterprise isolated SaaS"),
                    ("dedicated", "Dedicated/private"),
                ],
                default="shared",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="tenant_type",
            field=models.CharField(
                choices=[
                    ("platform", "Platform"),
                    ("audit_firm", "Audit firm"),
                    ("auditee", "Auditee organisation"),
                ],
                default="auditee",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="compliancegap",
            name="response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.assessmentresponse",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Organization administrator"),
                    ("ciso", "Security leader"),
                    ("architect", "Security architect"),
                    ("appsec", "Application security engineer"),
                    ("assessor", "Security assessor"),
                    ("developer", "Developer"),
                    ("manager", "Engineering manager"),
                    ("auditor", "Auditor"),
                    ("executive", "Executive"),
                    ("platform_admin", "Platform administrator"),
                    ("firm_admin", "Audit firm administrator"),
                    ("audit_manager", "Audit manager"),
                    ("reviewer", "Reviewer / QA"),
                    ("org_admin", "Auditee administrator"),
                    ("compliance_manager", "Compliance manager"),
                    ("control_owner", "Control owner"),
                    ("risk_owner", "Risk owner"),
                    ("vendor_manager", "Vendor manager"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="risklink",
            constraint=models.UniqueConstraint(
                fields=("tenant", "relationship", "source_type", "source_id"),
                name="risk_link_source_uniq",
            ),
        ),
        migrations.AddField(
            model_name="assessmentobservation",
            name="assessment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observations",
                to="core.assessment",
            ),
        ),
        migrations.AddField(
            model_name="assessmentobservation",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="auditorverdict",
            name="finalized_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="auditorverdict",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="superseded_by",
                to="core.auditorverdict",
            ),
        ),
        migrations.AddField(
            model_name="auditorverdict",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="controlassignment",
            name="assignee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="controlassignment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="controlevidencelink",
            name="evidence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="control_links",
                to="core.evidence",
            ),
        ),
        migrations.AddField(
            model_name="controlevidencelink",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="crosstenantaccessevent",
            name="target_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cross_tenant_access_events",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="crosstenantaccessevent",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="engagement",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="engagements_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="engagement",
            name="auditee_tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_engagements",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="engagement",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="engagements_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="engagement",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="crosstenantaccessevent",
            name="engagement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.engagement",
            ),
        ),
        migrations.AddField(
            model_name="engagementmember",
            name="engagement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="core.engagement",
            ),
        ),
        migrations.AddField(
            model_name="engagementmember",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="engagementmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="engagementscope",
            name="engagement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scopes",
                to="core.engagement",
            ),
        ),
        migrations.AddField(
            model_name="engagementscope",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="engagementstatushistory",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="engagementstatushistory",
            name="engagement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="status_history",
                to="core.engagement",
            ),
        ),
        migrations.AddField(
            model_name="engagementstatushistory",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="evidencerequirement",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="framework",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="frameworkversion",
            name="framework_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="core.framework",
            ),
        ),
        migrations.AddField(
            model_name="frameworkcontrolmapping",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="frameworkcontrolmapping",
            name="requirement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="control_mappings",
                to="core.requirement",
            ),
        ),
        migrations.AddField(
            model_name="frameworkcontrolmapping",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="organisationcontrol",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organisation_controls",
                to="core.application",
            ),
        ),
        migrations.AddField(
            model_name="organisationcontrol",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organisationcontrol",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="controlevidencelink",
            name="organisation_control",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidence_links",
                to="core.organisationcontrol",
            ),
        ),
        migrations.AddField(
            model_name="controlassignment",
            name="organisation_control",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="core.organisationcontrol",
            ),
        ),
        migrations.AddField(
            model_name="auditorverdict",
            name="organisation_control",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="auditor_verdicts",
                to="core.organisationcontrol",
            ),
        ),
        migrations.AddField(
            model_name="assessmentobservation",
            name="organisation_control",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observations",
                to="core.organisationcontrol",
            ),
        ),
        migrations.AddField(
            model_name="compliancegap",
            name="organisation_control",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gaps",
                to="core.organisationcontrol",
            ),
        ),
        migrations.AddConstraint(
            model_name="compliancegap",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_fingerprint__gt", "")),
                fields=("tenant", "source_fingerprint"),
                name="compliance_gap_fingerprint_uniq",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="gap",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="core.compliancegap",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="organisation_control",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="core.organisationcontrol",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="risk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks",
                to="core.risk",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="tenantbranding",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="tenantentitlement",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="tenantinvitation",
            name="invited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tenantinvitation",
            name="target_tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invitations",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="tenantinvitation",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="tenantrelationship",
            name="related_tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_relationships",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="tenantrelationship",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="tenantsubscription",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="unifiedcontrolobjective",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddField(
            model_name="organisationcontrol",
            name="unified_control",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organisation_controls",
                to="core.unifiedcontrolobjective",
            ),
        ),
        migrations.AddField(
            model_name="frameworkcontrolmapping",
            name="unified_control",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="framework_mappings",
                to="core.unifiedcontrolobjective",
            ),
        ),
        migrations.AddField(
            model_name="evidencerequirement",
            name="unified_control",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidence_requirements",
                to="core.unifiedcontrolobjective",
            ),
        ),
        migrations.AddField(
            model_name="usagerecord",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="engagement",
            constraint=models.UniqueConstraint(
                fields=("tenant", "reference"), name="engagement_reference_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="engagementmember",
            constraint=models.UniqueConstraint(
                fields=("tenant", "engagement", "user"), name="engagement_member_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="engagementscope",
            constraint=models.UniqueConstraint(
                fields=("tenant", "engagement", "scope_type", "object_reference"),
                name="engagement_scope_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="framework",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="framework_code_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="controlevidencelink",
            constraint=models.UniqueConstraint(
                fields=("tenant", "organisation_control", "source_type", "source_id"),
                name="control_evidence_source_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="controlassignment",
            constraint=models.UniqueConstraint(
                fields=("tenant", "organisation_control", "assignee"),
                name="control_assignment_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="auditorverdict",
            index=models.Index(
                fields=["tenant", "engagement_id", "organisation_control"],
                name="verdict_scope_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentobservation",
            constraint=models.UniqueConstraint(
                fields=("tenant", "source_type", "source_id"),
                name="observation_source_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionplan",
            constraint=models.UniqueConstraint(
                fields=("tenant", "key", "plan_version"), name="plan_version_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_id__isnull", False)),
                fields=("tenant", "task_type", "source_type", "source_id"),
                name="task_source_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantbranding",
            constraint=models.UniqueConstraint(
                fields=("tenant",), name="tenant_branding_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantentitlement",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="tenant_entitlement_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantrelationship",
            constraint=models.UniqueConstraint(
                fields=("tenant", "related_tenant", "relationship"),
                name="tenant_relationship_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="unifiedcontrolobjective",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code", "objective_version"), name="uco_version_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="organisationcontrol",
            constraint=models.UniqueConstraint(
                fields=("tenant", "application", "unified_control"),
                name="organisation_control_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="frameworkcontrolmapping",
            constraint=models.UniqueConstraint(
                fields=("tenant", "requirement", "unified_control"),
                name="framework_uco_mapping_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["tenant", "metric", "recorded_at"], name="usage_metric_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="usagerecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__gt", "")),
                fields=("tenant", "idempotency_key"),
                name="usage_idempotency_uniq",
            ),
        ),
    ]
