# Generated by Django 6.0.7 on 2026-07-31 10:28

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import os
import re
import uuid
from django.db import migrations, models


def secure_submission_receipts(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    quote = schema_editor.connection.ops.quote_name
    table = quote("core_repositorysubmission")
    expression = "tenant_id = NULLIF(current_setting('trishul.tenant_id', true), '')::uuid"
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        cursor.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        cursor.execute(f"CREATE POLICY tenant_isolation ON {table} USING ({expression}) WITH CHECK ({expression})")
        cursor.execute(
            f"ALTER TABLE {table} ADD CONSTRAINT same_tenant_repositorysubmission_repository "
            "FOREIGN KEY (repository_id, tenant_id) REFERENCES core_repository (id, tenant_id) "
            "DEFERRABLE INITIALLY DEFERRED"
        )
        app_role = os.getenv("TRISHUL_APP_DB_ROLE", "trishul_app")
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", app_role):
            raise RuntimeError("TRISHUL_APP_DB_ROLE is not a valid PostgreSQL role name")
        cursor.execute("SELECT 1 FROM pg_roles WHERE rolname = %s", [app_role])
        if cursor.fetchone():
            cursor.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO {quote(app_role)}")


def unsecure_submission_receipts(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("DROP POLICY IF EXISTS tenant_isolation ON core_repositorysubmission")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_job_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositoryversion",
            name="archive_validation_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repositoryversion",
            name="archive_validation_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repositoryversion",
            name="submission_received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scan",
            name="analysis_queued_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="scan",
            name="analysis_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scan",
            name="analysis_terminated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scan",
            name="final_review_outcome_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scan",
            name="findings_persisted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scan",
            name="first_analyst_review_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scan",
            name="risk_workflow_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RepositorySubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("validation_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "validation_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("validation_outcome", models.CharField(blank=True, max_length=20)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.repository",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(secure_submission_receipts, unsecure_submission_receipts),
    ]
