# Generated by Django 6.0.7 on 2026-07-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_job_application"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="findingevidence",
            options={},
        ),
        migrations.AlterModelOptions(
            name="job",
            options={},
        ),
        migrations.AddField(
            model_name="job",
            name="dispatch_pending",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="job",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="scan",
            name="configuration",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="scan",
            name="enabled_rules",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name="findingevidence",
            constraint=models.UniqueConstraint(
                fields=("tenant", "finding", "file_path", "start_line", "end_line"),
                name="finding_evidence_location_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("idempotency_key__gt", ""),
                    ("state__in", ["queued", "running", "completed"]),
                ),
                fields=("tenant", "idempotency_key"),
                name="job_active_idempotency_uniq",
            ),
        ),
    ]
