# Generated by Django 6.0.7 on 2026-08-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_evidence_single_successor"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="extracted_attributes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="evidence",
            name="extraction_confidence",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name="evidence",
            name="extraction_provenance",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="evidence",
            name="media_type",
            field=models.CharField(default="application/octet-stream", max_length=100),
        ),
        migrations.AddField(
            model_name="evidence",
            name="quality_breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="evidence",
            name="quality_passed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evidence",
            name="quality_profile_version",
            field=models.CharField(default="evidence-quality-1.0", max_length=80),
        ),
        migrations.AddField(
            model_name="evidence",
            name="quality_reasons",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="evidence",
            name="quality_score",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="evidence",
            name="quality_suggestions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="evidence",
            name="quality_threshold",
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=3),
        ),
    ]
