# Generated by Django 6.0.7 on 2026-08-10 10:50

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_evidence_extracted_attributes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="audit_period_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="audit_period_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessment",
            name="scope",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="compliancegap",
            name="details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="compliancegap",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="compliancegap",
            name="evidence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gaps",
                to="core.evidence",
            ),
        ),
        migrations.AddField(
            model_name="compliancegap",
            name="failed_check",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="compliancegap",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="compliancegap",
            name="requirement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.requirement",
            ),
        ),
        migrations.CreateModel(
            name="EvidenceReuseEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "mapping_coverage",
                    models.CharField(
                        choices=[
                            ("full", "Full"),
                            ("partial", "Partial"),
                            ("supporting", "Supporting"),
                            ("none", "None"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("accept", "Accept"),
                            ("accept_review_suggested", "Accept, review suggested"),
                            ("partial", "Partial"),
                            ("reject_stale", "Reject: stale"),
                            ("reject_out_of_scope", "Reject: out of scope"),
                            ("reject_insufficient", "Reject: insufficient"),
                            ("reject_low_quality", "Reject: low quality"),
                            ("duplicate", "Duplicate"),
                        ],
                        max_length=40,
                    ),
                ),
                ("checks", models.JSONField(blank=True, default=list)),
                ("reasons", models.JSONField(blank=True, default=list)),
                (
                    "engine_version",
                    models.CharField(default="deterministic-reuse-1.0", max_length=40),
                ),
                (
                    "confidence",
                    models.DecimalField(decimal_places=3, default=1, max_digits=4),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reuse_evaluations",
                        to="core.evidence",
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.frameworkcontrolmapping",
                    ),
                ),
                (
                    "organisation_control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reuse_evaluations",
                        to="core.organisationcontrol",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reuse_evaluations",
                        to="core.requirement",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
                (
                    "unified_control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reuse_evaluations",
                        to="core.unifiedcontrolobjective",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
