# Generated by Django 6.0.7 on 2026-08-10 11:44

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_evidence_lifecycle_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityProviderConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "protocol",
                    models.CharField(
                        choices=[("oidc", "OpenID Connect"), ("saml", "SAML 2.0")],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("issuer", models.URLField()),
                ("discovery_url", models.URLField(blank=True)),
                ("client_id", models.CharField(blank=True, max_length=200)),
                ("audience", models.CharField(blank=True, max_length=200)),
                ("jwks_url", models.URLField(blank=True)),
                ("metadata_url", models.URLField(blank=True)),
                ("secret_reference", models.CharField(blank=True, max_length=300)),
                ("attribute_mapping", models.JSONField(blank=True, default=dict)),
                ("mfa_required", models.BooleanField(default=True)),
                ("allowed_acr_values", models.JSONField(blank=True, default=list)),
                ("enabled", models.BooleanField(default=False)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "protocol"),
                        name="tenant_identity_protocol_uniq",
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="TenantSessionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("idle_timeout_minutes", models.PositiveIntegerField(default=30)),
                ("absolute_timeout_minutes", models.PositiveIntegerField(default=720)),
                (
                    "max_concurrent_sessions",
                    models.PositiveSmallIntegerField(default=5),
                ),
                ("require_mfa", models.BooleanField(default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.tenant"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant",), name="tenant_session_policy_uniq"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
