# Generated by Django 6.0.7 on 2026-08-11 09:19

import os
import re

from django.db import migrations, models


DELEGATED_TABLES = ("core_tenantsubscription", "core_tenantentitlement", "core_organization", "core_workspace")


def drop_role_policies(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP POLICY IF EXISTS platform_or_firm_tenant_create ON core_tenant")
        cursor.execute("DROP POLICY IF EXISTS platform_tenant_update ON core_tenant")
        for table in DELEGATED_TABLES:
            cursor.execute(f"DROP POLICY IF EXISTS delegated_onboarding ON {table}")


def restore_role_policies(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    app_role = os.getenv("TRISHUL_APP_DB_ROLE", "trishul_app")
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", app_role):
        raise RuntimeError("TRISHUL_APP_DB_ROLE is not a valid PostgreSQL role name")
    q = schema_editor.connection.ops.quote_name
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT 1 FROM pg_roles WHERE rolname = %s", [app_role])
        if not cursor.fetchone():
            return
        role = q(app_role)
        cursor.execute(
            f"CREATE POLICY platform_or_firm_tenant_create ON core_tenant FOR INSERT TO {role} WITH CHECK ("
            "EXISTS (SELECT 1 FROM core_membership m WHERE "
            "m.tenant_id = NULLIF(current_setting('trishul.tenant_id', true), '')::uuid "
            "AND m.user_id = NULLIF(current_setting('trishul.user_id', true), '')::integer AND m.is_active "
            "AND ((m.role = 'platform_admin' AND tenant_type = 'audit_firm') "
            "OR (m.role IN ('firm_admin', 'audit_manager') AND tenant_type = 'auditee'))))"
        )
        cursor.execute(
            f"CREATE POLICY platform_tenant_update ON core_tenant FOR UPDATE TO {role} USING ("
            "EXISTS (SELECT 1 FROM core_membership m WHERE "
            "m.tenant_id = NULLIF(current_setting('trishul.tenant_id', true), '')::uuid "
            "AND m.user_id = NULLIF(current_setting('trishul.user_id', true), '')::integer "
            "AND m.is_active AND m.role = 'platform_admin'))"
        )
        delegated = (
            "EXISTS (SELECT 1 FROM core_membership m JOIN core_tenant target ON target.id = tenant_id WHERE "
            "m.tenant_id = NULLIF(current_setting('trishul.tenant_id', true), '')::uuid "
            "AND m.user_id = NULLIF(current_setting('trishul.user_id', true), '')::integer AND m.is_active "
            "AND ((m.role = 'platform_admin' AND target.tenant_type = 'audit_firm') "
            "OR (m.role IN ('firm_admin', 'audit_manager') AND target.tenant_type = 'auditee')))"
        )
        for table in DELEGATED_TABLES:
            cursor.execute(
                f"CREATE POLICY delegated_onboarding ON {table} FOR INSERT TO {role} WITH CHECK ({delegated})"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_custom_roles"),
    ]

    operations = [
        migrations.RunPython(drop_role_policies, restore_role_policies),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Organization administrator"),
                    ("ciso", "Security leader"),
                    ("architect", "Security architect"),
                    ("appsec", "Application security engineer"),
                    ("assessor", "Security assessor"),
                    ("developer", "Developer"),
                    ("manager", "Engineering manager"),
                    ("auditor", "Auditor"),
                    ("executive", "Executive"),
                    ("platform_admin", "Platform administrator"),
                    ("framework_content_manager", "Framework content manager"),
                    ("firm_admin", "Audit firm administrator"),
                    ("audit_manager", "Audit manager"),
                    ("lead_auditor", "Lead auditor"),
                    ("reviewer", "Reviewer / QA"),
                    ("org_admin", "Auditee administrator"),
                    ("compliance_manager", "Compliance manager"),
                    ("control_owner", "Control owner"),
                    ("risk_owner", "Risk owner"),
                    ("vendor_manager", "Vendor manager"),
                    ("policy_approver", "Policy approver"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="scimcredential",
            name="default_role",
            field=models.CharField(
                choices=[
                    ("admin", "Organization administrator"),
                    ("ciso", "Security leader"),
                    ("architect", "Security architect"),
                    ("appsec", "Application security engineer"),
                    ("assessor", "Security assessor"),
                    ("developer", "Developer"),
                    ("manager", "Engineering manager"),
                    ("auditor", "Auditor"),
                    ("executive", "Executive"),
                    ("platform_admin", "Platform administrator"),
                    ("framework_content_manager", "Framework content manager"),
                    ("firm_admin", "Audit firm administrator"),
                    ("audit_manager", "Audit manager"),
                    ("lead_auditor", "Lead auditor"),
                    ("reviewer", "Reviewer / QA"),
                    ("org_admin", "Auditee administrator"),
                    ("compliance_manager", "Compliance manager"),
                    ("control_owner", "Control owner"),
                    ("risk_owner", "Risk owner"),
                    ("vendor_manager", "Vendor manager"),
                    ("policy_approver", "Policy approver"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="tenantinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Organization administrator"),
                    ("ciso", "Security leader"),
                    ("architect", "Security architect"),
                    ("appsec", "Application security engineer"),
                    ("assessor", "Security assessor"),
                    ("developer", "Developer"),
                    ("manager", "Engineering manager"),
                    ("auditor", "Auditor"),
                    ("executive", "Executive"),
                    ("platform_admin", "Platform administrator"),
                    ("framework_content_manager", "Framework content manager"),
                    ("firm_admin", "Audit firm administrator"),
                    ("audit_manager", "Audit manager"),
                    ("lead_auditor", "Lead auditor"),
                    ("reviewer", "Reviewer / QA"),
                    ("org_admin", "Auditee administrator"),
                    ("compliance_manager", "Compliance manager"),
                    ("control_owner", "Control owner"),
                    ("risk_owner", "Risk owner"),
                    ("vendor_manager", "Vendor manager"),
                    ("policy_approver", "Policy approver"),
                ],
                max_length=30,
            ),
        ),
        migrations.RunPython(restore_role_policies, drop_role_policies),
    ]
