# Generated by Django 6.0.7 on 2026-08-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_custom_role_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="crosstenantaccessevent",
            name="application_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="crosstenantaccessevent",
            name="correlation_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
